# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a827377bb5d282631e84b060d4a367ae278c01284a8071e38e9826d369b48114f0b42e8479d60923ccc0c629d6850fa73b436a00edc4570c77e8fec64d15f1d

test:
  secret_key_base: 87d525cec9681380244ce10c0563e48d7728d29c78b610c3d80f91d2341c06c468c50e7f371d89010566f1fcc68513f82464531760ceeb3ef15d89587d9482a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
